[package]
name = "manul"
version = "0.1.0"
edition = "2021"
authors = ['Entropy Cryptography <engineering@entropy.xyz>']
license = "AGPL-3.0-or-later"
description = "Generic library for round-based protocols"
repository = "https://github.com/entropyxyz/manul"
readme = "../README.md"
categories = ["cryptography", "no-std"]

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "serde_derive"] }
digest = { version = "0.10", default-features = false, optional = true }
signature = { version = "2", default-features = false, features = ["digest"], optional = true }
rand_core = { version = "0.6.4", default-features = false }
rand = { version = "0.8", default-features = false }
tracing = { version = "0.1", default-features = false }
displaydoc = { version = "0.2", default-features = false }

[dev-dependencies]
impls = "1"

[features]
rustcrypto-traits = ["digest", "signature"]
